name: mmoInfoWorld
main: mmo.Info.mmoInfoWorld.MMOInfoWorld
version: 1.2
website: https://github.com/mmoMinecraftDev/mmoInfoWorld
author: dotblank <dotblank@precipicegames.com>, Dockter, Pamelloes, Rycochet
depend: [Spout,mmoCore]

description: Provides a display in mmoInfo for the current world
