name: mmoInfoWorld
version: ${releaseVersion}.${buildNumber}
description: Adds a {world} token to the mmoInfo token list for the current world a player is in.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Info.mmoInfoWorld.MMOInfoWorld
depend: [Spout, mmoCore]
